CREATE TABLE User (
  id_usr MEDIUMINT NOT NULL AUTO_INCREMENT,
  id_original_usr VARCHAR(30) NOT NULL,
  name_usr VARCHAR(50) NOT NULL,
  yelping_since_usr DATE NOT NULL,
  review_count_usr SMALLINT NOT NULL,
  fans_usr SMALLINT NOT NULL,
  type_usr VARCHAR(20) NOT NULL,
  avg_stars_usr FLOAT(6,5),
  votes_funny_usr SMALLINT,
  votes_useful_usr SMALLINT,
  votes_cool_usr SMALLINT,
  compliments_profile_usr SMALLINT,
  compliments_cute_usr SMALLINT,
  compliments_funny SMALLINT,
  compliments_plain_usr SMALLINT,
  compliments_writer_usr SMALLINT,
  compliments_note_usr SMALLINT,
  compliments_photos_usr SMALLINT,
  compliments_hot_usr SMALLINT,
  compliments_cool_usr SMALLINT,
  compliments_more_usr SMALLINT,
  PRIMARY KEY(id_usr)
);