CREATE TABLE User (
  id_usr MEDIUMINT NOT NULL AUTO_INCREMENT,
  id_original_usr VARCHAR(30) NOT NULL,
  name_usr VARCHAR(50) NOT NULL,
  yelping_since_usr DATE NOT NULL,
  review_count_usr MEDIUMINT NOT NULL,
  fans_usr MEDIUMINT NOT NULL,
  type_usr VARCHAR(20) NOT NULL,
  avg_stars_usr FLOAT(6,5),
  votes_funny_usr MEDIUMINT,
  votes_useful_usr MEDIUMINT,
  votes_cool_usr MEDIUMINT,
  compliments_profile_usr MEDIUMINT,
  compliments_cute_usr MEDIUMINT,
  compliments_funny MEDIUMINT,
  compliments_plain_usr MEDIUMINT,
  compliments_writer_usr MEDIUMINT,
  compliments_note_usr MEDIUMINT,
  compliments_photos_usr MEDIUMINT,
  compliments_hot_usr MEDIUMINT,
  compliments_cool_usr MEDIUMINT,
  compliments_more_usr MEDIUMINT,
  PRIMARY KEY(id_usr)
);

CREATE TABLE Business (
  id_bus MEDIUMINT NOT NULL AUTO_INCREMENT,
  id_original_bus VARCHAR(30) NOT NULL,
  name_bus VARCHAR(80) NOT NULL,
  type_bus VARCHAR(20) NOT NULL,
  city_bus VARCHAR(50) NOT NULL,
  state_bus VARCHAR(3) NOT NULL,
  address_bus VARCHAR(60),
  open_bus TINYINT(1) NOT NULL,
  review_count_bus MEDIUMINT NOT NULL,
  stars_bus FLOAT(2,1) NOT NULL,
  latitude_bus FLOAT(11,8) NOT NULL,
  longitude_bus FLOAT(11,8) NOT NULL,
  PRIMARY KEY(id_bus)
);